# CLIENTE #

### Criação de um novo Cliente
POST http://localhost:5088/cliente/cadastrar
Content-Type: application/json

{
    "nome": "Cliente1",
    "endereco": "Rua do cliente 1",
    "email": "cliente1@email.com",
    "telefone" : "99543-6421"
}

### Listar todos os clientes
GET http://localhost:5088/cliente/listar

### Deletar cliente
DELETE http://localhost:5088/cliente/deletar/0f168033-c4f5-406a-b86f-11fddc1f06d0


### Alterar Cliente
PUT http://localhost:5088/cliente/atualizar/Cliente1
Content-Type: application/json

{
    "nome": "ClienteAtualizado",
    "endereco": "Rua do cliente 1Atualizado",
    "email": "clienteAtualizado@email.com",
    "telefone" : "99876-2222"
}

# FILMES #

### Criação de um novo Filme
POST http://localhost:5088/filme/cadastrar
Content-Type: application/json

{
    "titulo": "Filme1",
    "diretor": "Diretor do Filme 1",
    "ano": "2024",
    "status" : "Alugado"
}

### Listar todos os Filmes
GET http://localhost:5088/filme/listar

### Deletar Filme
DELETE http://localhost:5088/filme/deletar/ba6246a0-21f8-43f1-a67a-2de6ba9af63d


### Alterar Filme
PUT http://localhost:5088/filme/atualizar/ba6246a0-21f8-43f1-a67a-2de6ba9af63d
Content-Type: application/json

{
    "titulo": "FilmeAtualizado",
    "diretor": "Diretor do Filme Atualizado",
    "ano": "2023",
    "status" : "Disponivel"
}
